# Generated by Django 3.2.15 on 2022-09-22 17:12

import core.tools
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('nomeAutor', models.TextField(primary_key=True, serialize=False)),
                ('siglaTipoAutor', models.CharField(max_length=200)),
                ('descricaoTipoAutor', models.CharField(max_length=200)),
                ('numOrdemAutor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('codigoClasse', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricaoClasse', models.CharField(max_length=200)),
                ('descricaoClasseHierarquica', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComissaoComposicaoAtualMista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='ComissaoComposicaoResumidaMistaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('dataFim', models.CharField(max_length=8)),
                ('dataInicio', models.CharField(max_length=8)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='ComissaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('codigoEmenda', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numeroEmenda', models.CharField(max_length=20)),
                ('dataApresentacao', models.DateField()),
                ('colegiadoApresentacao', models.CharField(max_length=20)),
                ('descricaoTurno', models.CharField(max_length=100)),
                ('descricaoTipoEmenda', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(help_text='path', max_length=4)),
                ('mes', models.CharField(help_text='path', max_length=2)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='IndexacaoMateria',
            fields=[
                ('index', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='LegislacaoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoseq', models.BigIntegerField()),
                ('numdata', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='LegislacaoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=8)),
                ('ident', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('reedicao', models.BigIntegerField()),
                ('seq', models.BigIntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='LegislacaoTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaAtualizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('numdias', models.BigIntegerField(default=30)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaAutoria',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaDistribuicaoAutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codParlamentar', models.CharField(max_length=20)),
                ('siglaComissao', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaDistribuicaoAutoriaComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codParlamentar', models.CharField(max_length=20)),
                ('siglaComissao', models.CharField(max_length=20)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaEmendas',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaLegislaturaAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('numero', models.BigIntegerField()),
                ('sigla', models.CharField(max_length=50)),
                ('tramitando', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaListaPrazo',
            fields=[
                ('codPrazo', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('comissao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaMovimentacoes',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataref', models.CharField(max_length=8)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaRelatorias',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaTextos',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaTramintando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('data', models.CharField(max_length=8)),
                ('hora', models.CharField(max_length=6)),
                ('numero', models.BigIntegerField()),
                ('sigla', models.CharField(max_length=50)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaVotacoes',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('v', models.IntegerField()),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='NaturezaMateria',
            fields=[
                ('codigoNatureza', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomeNatureza', models.CharField(max_length=100)),
                ('descricaoNatureza', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PesquisaMateriaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('anoNorma', models.CharField(max_length=4)),
                ('codigoClasse', models.BigIntegerField()),
                ('codigoConteudo', models.BigIntegerField()),
                ('dataFimApresentacao', models.CharField(max_length=8)),
                ('dataInicioApresentacao', models.CharField(max_length=8)),
                ('nomeAutor', models.TextField()),
                ('numero', models.BigIntegerField()),
                ('numeroNorma', models.BigIntegerField()),
                ('palavraChave', models.TextField()),
                ('sigla', models.CharField(max_length=50)),
                ('siglaComissaoReq', models.CharField(max_length=50)),
                ('tipoNorma', models.CharField(max_length=50)),
                ('tramitando', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='PlenarioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=8)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='PlenarioLegislaturaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataSessaoLeg', models.CharField(max_length=8)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='PlenarioListaDiscursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFim', models.CharField(max_length=8)),
                ('dataInicio', models.CharField(max_length=8)),
                ('siglaCasa', models.CharField(max_length=2)),
                ('numeroSessao', models.CharField(max_length=10)),
                ('tipoSessao', models.CharField(max_length=10)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='PlenarioResultadoVeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='PlenarioResultadoVetoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='PlenarioResultadoVetoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='Senador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorApartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('casa', models.CharField(max_length=2)),
                ('dataFim', models.CharField(max_length=8)),
                ('dataInicio', models.CharField(max_length=8)),
                ('numeroSessao', models.CharField(max_length=10)),
                ('tipoSessao', models.CharField(max_length=10)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorAutorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=10)),
                ('primeiro', models.CharField(max_length=1)),
                ('sigla', models.CharField(max_length=20)),
                ('tramitando', models.CharField(max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorCargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('comissao', models.CharField(max_length=20)),
                ('indAtivos', models.CharField(max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorComissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('comissao', models.CharField(max_length=20)),
                ('indAtivos', models.CharField(max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorDiscursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('casa', models.CharField(max_length=2)),
                ('dataFim', models.CharField(max_length=8)),
                ('dataInicio', models.CharField(max_length=8)),
                ('numeroSessao', models.CharField(max_length=10)),
                ('tipoSessao', models.CharField(max_length=10)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorFiliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorLiderancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorListaLegislatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.BigIntegerField()),
                ('exercicio', models.CharField(max_length=1)),
                ('participacao', models.CharField(max_length=1)),
                ('uf', models.CharField(max_length=2)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorListaLegislaturaIntervalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislaturaFim', models.BigIntegerField()),
                ('legislaturaInicio', models.BigIntegerField()),
                ('exercicio', models.CharField(max_length=1)),
                ('participacao', models.CharField(max_length=1)),
                ('uf', models.CharField(max_length=2)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorMandatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorRelatorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('comissao', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('sigla', models.CharField(max_length=20)),
                ('tramitando', models.CharField(max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='SenadorVotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('numero', models.BigIntegerField()),
                ('sigla', models.CharField(max_length=50)),
                ('tramitando', models.CharField(max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('codigoParlamentar', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nomeParlamentar', models.TextField()),
                ('nomeCompletoParlamentar', models.TextField()),
                ('sexoParlamentar', models.CharField(max_length=20)),
                ('formaTratamento', models.CharField(max_length=50, null=True)),
                ('urlFotoParlamentar', models.URLField(null=True)),
                ('urlPaginaParlamentar', models.URLField(null=True)),
                ('emailParlamentar', models.EmailField(max_length=254, null=True)),
                ('siglaPartidoParlamentar', models.CharField(max_length=100, null=True)),
                ('ufParlamentar', models.CharField(max_length=10, null=True)),
                ('autoria', models.ManyToManyField(to='senado.Autoria')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('identificacaoProcesso', models.CharField(max_length=20, null=True)),
                ('descricaoIdentificacao', models.CharField(max_length=100, null=True)),
                ('sigla', models.CharField(max_length=10, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('ano', models.CharField(max_length=4, null=True)),
                ('siglaComissao', models.CharField(max_length=20, null=True)),
                ('ementa', models.TextField(null=True)),
                ('autor', models.TextField(null=True)),
                ('data', models.DateField(null=True)),
                ('urlDetalheMateria', models.URLField(null=True)),
                ('assunto', models.ManyToManyField(to='senado.Assunto')),
                ('autoria', models.ManyToManyField(to='senado.Autoria')),
                ('classificacao', models.ManyToManyField(to='senado.Classificacao')),
                ('emenda', models.ManyToManyField(to='senado.Emenda')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senado.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Decisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('sigla', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senado.materia')),
            ],
        ),
        migrations.CreateModel(
            name='DadosBasicosMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ementaMateria', models.TextField()),
                ('explicacaoEmentaMateria', models.TextField()),
                ('apelidoMateria', models.TextField()),
                ('casaIniciadoraNoLegislativo', models.CharField(max_length=50)),
                ('indicadorComplementar', models.CharField(max_length=50)),
                ('dataApresentacao', models.DateField()),
                ('siglaCasaLeitura', models.CharField(max_length=50)),
                ('indexacaoMateria', models.ManyToManyField(to='senado.IndexacaoMateria')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senado.materia')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='senado.naturezamateria')),
            ],
        ),
    ]
