# Generated by Django 3.2.15 on 2022-08-03 14:51

import core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoriaRequest',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
        migrations.CreateModel(
            name='MateriaPesquisaLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('anoNorma', models.CharField(max_length=4)),
                ('codigoClasse', models.BigIntegerField()),
                ('codigoConteudo', models.BigIntegerField()),
                ('dataFimApresentacao', models.CharField(max_length=8)),
                ('dataInicioApresentacao', models.CharField(max_length=8)),
                ('nomeAutor', models.TextField()),
                ('numero', models.BigIntegerField()),
                ('numeroNorma', models.BigIntegerField()),
                ('palavraChave', models.TextField()),
                ('sigla', models.CharField(max_length=50)),
                ('siglaComissaoReq', models.CharField(max_length=50)),
                ('tipoNorma', models.CharField(max_length=50)),
                ('tramitando', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, core.tools.Request),
        ),
    ]
