# Generated by Django 3.2.15 on 2022-08-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriaPesquisaLista',
            new_name='PesquisaMateriaService',
        ),
    ]
