# Generated by Django 3.2.16 on 2022-10-09 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='OrigemMateria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='senado.origemmateria'),
        ),
    ]
