# Generated by Django 3.2.16 on 2022-10-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0002_alter_materia_origemmateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='MateriaAnexada',
            field=models.ManyToManyField(related_name='Anexada', to='senado.Materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='MateriaRelacionada',
            field=models.ManyToManyField(related_name='Relacionada', to='senado.Materia'),
        ),
    ]
