# Generated by Django 3.2.16 on 2022-10-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0003_auto_20221009_2349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformesLegislativo',
            new_name='InformeLegislativo',
        ),
        migrations.RemoveField(
            model_name='autuacao',
            name='InformesLegislativo',
        ),
        migrations.AddField(
            model_name='autuacao',
            name='InformeLegislativo',
            field=models.ManyToManyField(to='senado.InformeLegislativo'),
        ),
    ]
