# Generated by Django 3.2.16 on 2022-10-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0004_auto_20221010_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegiado',
            fields=[
                ('CodigoColegiado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SiglaColegiado', models.CharField(max_length=50)),
                ('NomeColegiado', models.TextField()),
                ('SiglaCasaColegiado', models.CharField(max_length=50)),
                ('NomeCasaColegiado', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='informelegislativo',
            name='Colegiado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='senado.colegiado'),
            preserve_default=False,
        ),
    ]
