# Generated by Django 3.2.16 on 2022-10-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0007_alter_informelegislativo_codigotramitacaolegado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informelegislativo',
            name='Colegiado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='senado.colegiado'),
        ),
    ]
