# Generated by Django 3.2.16 on 2022-10-10 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senado', '0008_alter_informelegislativo_colegiado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informelegislativo',
            name='SituacaoIniciada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='senado.situacaoiniciada'),
        ),
    ]
