# Generated by Django 4.0.2 on 2022-02-26 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_materia_id_alter_materia_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('codigoParlamentar', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigoPublicoNaLegAtual', models.BigIntegerField()),
                ('codigoDeputadoNaCamara', models.BigIntegerField()),
                ('nomeParlamentar', models.CharField(max_length=100)),
                ('nomeCompletoParlamentar', models.CharField(max_length=100)),
                ('sexoParlamentar', models.CharField(max_length=100)),
                ('formaTratamento', models.CharField(max_length=100)),
                ('emailParlamentar', models.EmailField(max_length=254)),
                ('siglaPartidoParlamentar', models.CharField(max_length=100)),
                ('ufParlamentar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglaTipoIniciativa', models.CharField(max_length=100)),
                ('descricaoTipoIniciativa', models.CharField(max_length=100)),
                ('descricaoIniciativa', models.CharField(max_length=100)),
                ('identificacaoParlamentar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.parlamentar')),
                ('materia', models.ManyToManyField(to='database.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAutor', models.CharField(max_length=100)),
                ('siglaTipoAutor', models.CharField(max_length=100)),
                ('descricaoTipoAutor', models.CharField(max_length=100)),
                ('numOrdemAutor', models.IntegerField()),
                ('materia', models.ManyToManyField(to='database.Materia')),
            ],
        ),
    ]
