# Generated by Django 4.0.2 on 2022-02-26 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_iniciativa_identificacaoparlamentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoria',
            name='identificacaoParlamentar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.parlamentar'),
        ),
    ]
