# Generated by Django 4.0.2 on 2022-02-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_autoria_identificacaoparlamentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='codigoDeputadoNaCamara',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='codigoPublicoNaLegAtual',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='emailParlamentar',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='siglaPartidoParlamentar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='ufParlamentar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
