
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
kibana.autocompleteTerminateAfter: 30000000
kibana.autocompleteTimeout: 10000000