# Generated by Django 4.0.2 on 2022-02-17 15:17

from django.db import migrations, models
import request.request


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPesquisaLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('anoNorma', models.CharField(max_length=4)),
                ('codigoClasse', models.BigIntegerField()),
                ('codigoConteudo', models.BigIntegerField()),
                ('dataFimApresentacao', models.CharField(max_length=8)),
                ('dataInicioApresentacao', models.CharField(max_length=8)),
                ('nomeAutor', models.TextField()),
                ('numero', models.BigIntegerField()),
                ('numeroNorma', models.BigIntegerField()),
                ('palavraChave', models.TextField()),
                ('sigla', models.CharField(max_length=50)),
                ('siglaComissaoReq', models.CharField(max_length=50)),
                ('tipoNorma', models.CharField(max_length=50)),
                ('tramitando', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('v', models.CharField(max_length=10)),
            ],
            bases=(models.Model, request.request.Request),
        ),
    ]
