# Generated by Django 4.0.2 on 2022-02-26 02:37

from django.db import migrations, models
import request.request


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoriaRequest',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            bases=(models.Model, request.request.Request),
        ),
    ]
